### ISSUE TITLE
Change GuruBu favicon with the new one

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#112]
Icon: https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=577-6755&mode=design&t=ht1KNnWJsFlH2kWu-0

**Comment by mevlutcantuna** [comment]
Hi @armagandalkiran,

I would like to implement this issue, could you please assign it to me?

**Comment by armagandalkiran** [comment]
I assigned it to you thank you 🤘 @mevlutcantuna
