### ISSUE TITLE
Navbar on mobile should be full width

### ISSUE THREAD

**Issue by emretfn** [Trendyol/gurubu#118]
In the mobile view, the navbar does not take up the entire width. I would like to fix this. If you have a design for mobile, I would appreciate it if you could share it.

![image](https://github.com/Trendyol/gurubu/assets/14194501/8be23819-8c32-49f2-bc41-5bbae2c89d31)

**Comment by armagandalkiran** [comment]
Nice catch thank you! Of course you can implement it but do you need design for this ? full width will be fine for us i think 🤘. @aahmetcakir  what do you think ?

**Comment by emretfn** [comment]
In its current state, it has different padding values than the desktop view. I can keep the padding values in Desktop or give a specific padding value. That's why I asked if you have a design. @armagandalkiran

**Comment by mertcanaltin** [comment]
> In its current state, it has different padding values than the desktop view. I can keep the padding values in Desktop or give a specific padding value. That's why I asked if you have a design. @armagandalkiran

Can you open a pr about this?
you can create pr at any time please feel free 🚀
