### ISSUE TITLE
Displaying an error page instead of breaking the app at runtime?

### ISSUE THREAD

**Issue by hanifisenturk** [Trendyol/gurubu#33]
Hi @armagandalkiran,
I've noticed that there is no error handling for the entire app. When users encounter an error at runtime, it would be beneficial to display a meaningful error page to them.

Here is the related documentation that we can use as a guide:
[https://nextjs.org/docs/app/building-your-application/routing/error-handling](https://nextjs.org/docs/app/building-your-application/routing/error-handling)

**Comment by batuhanbaybas** [comment]
if there is a design for error page i can implement this on project

**Comment by aahmetcakir** [comment]
Hi @batuhanbaybas you can implement design on this [link](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/Untitled?type=design&node-id=0%3A1&mode=design&t=M3jCHD2p85YGhORX-1)
if you didn't see spacing attributes you can fork design file to your account.
