### ISSUE TITLE
Implement new landing page first section according to new ui design

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#53]
### Tasks

# Implement new landing page first section according to new ui design

## Why do we need this?

We want to transition to a more innovative and user-friendly design compared to the old one, aiming to increase user attention.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

- Only the first section of the landing page should implemented including navbar.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/Error-pages-%2361?type=design&node-id=17-10511&mode=design&t=ctrRHO8cwbCnvsFU-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by hanifisenturk** [comment]
Hi guys! @armagandalkiran @aahmetcakir

I want to create a hero section with a navbar. I also have a question about the navbar: does the navbar need to have a sticky position?

**Comment by armagandalkiran** [comment]
Hi there! Sticky will be good. You can assign this issue yourself if you want to.

**Comment by hanifisenturk** [comment]
Yes, I would appreciate it if you assign this to me :)

**Comment by armagandalkiran** [comment]
Hi @hanifisenturk ! Did you need assist here ? How is everything going ? 🚀

**Comment by hanifisenturk** [comment]
Hi! @armagandalkiran!  I currently have a heavy workload. I plan to ship it tonight.
