### ISSUE TITLE
Implement grooming navbar according to new ui design

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#57]
### Tasks

# Implement grooming navbar according to new ui design

## Why do we need this?

We want to transition to a more innovative and user-friendly design compared to the old one, aiming to increase user attention.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

- Only the navbar should be implemented in the design. ( including participants here, copy link and user name field )

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=31-4056&mode=design&t=UteNBAQVWXCmz81r-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by emrerenJs** [comment]
Hey everyone!

a) Are we expecting to animate 2 interaction buttons (Copy Link and User Button) in the Navbar section on hover? I found only the Badge variant in the [Figma](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=31-4056&mode=design&t=hDUd5C8pvfsBuDUE-0) file.

b) What we are expecting about the color of the copied icon when clicking the "Copy Link" button? 

c) The icons that are used inside [the action buttons](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=31-4056&mode=design&t=hDUd5C8pvfsBuDUE-0) on the Navbar do not exist in the Tabler Icons library. Should I implement the icons as SVG?

Thanks for your answers!

**Comment by armagandalkiran** [comment]
:fyi: @aahmetcakir

**Comment by armagandalkiran** [comment]
I can answer c) here, yes we can implement it as svg we change our icons. In the end of v2 ui ehnancement, we are going to delete tabler icons package.

**Comment by aahmetcakir** [comment]
For now, you can only do what you see in the design. In general, we did not work as a variant in figma, so we do not have a general structure to answer this question. If you do what you see in the design, it will be enough for us. @emrerenJs
