### ISSUE TITLE
Establishing Error Page Structure

### ISSUE THREAD

**Issue by aahmetcakir** [Trendyol/gurubu#61]
### Tasks

# Establishing Error Page Structure

## Why do we need this?

When a user encounters an error, we aim to avoid directing them to the 'next' error page. Instead, we prefer to present commonly used and simple 404 and 500 pages, rather than exposing the error directly to the user.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/Error-pages-%2361?type=design&node-id=1-2410&mode=design&t=TVPpFOwcuw0IsUez-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by hsglc** [comment]
@armagandalkiran Is the design given above only for 404 pages? It seems like the design of the error page should be different?

**Comment by armagandalkiran** [comment]
We thought that we proceed with the same UI, different status code for two errors. @aahmetcakir right ?

**Comment by aahmetcakir** [comment]
That's right kardo. We can continue with same UI. @hsglc fyi
