### ISSUE TITLE
Implement new landing page second section according to new ui design

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#62]
### Tasks

# Implement new landing page first section according to new ui design

## Why do we need this?

We want to transition to a more innovative and user-friendly design compared to the old one, aiming to increase user attention.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

- Only the second section of the landing page should implemented.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/Error-pages-%2361?type=design&node-id=17-55939&mode=design&t=ctrRHO8cwbCnvsFU-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by mevlutcantuna** [comment]
Hey guys @armagandalkiran  @Acanguven,

I would like to implement the second section of the landing page, could you please assign me the issue?

**Comment by armagandalkiran** [comment]
I assigned it 🚀

**Comment by mevlutcantuna** [comment]
Thanks @armagandalkiran  

I’ve opened a pull request for this issue.
