### ISSUE TITLE
Implement new landing page fourth section according to new ui design

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#64]
### Tasks

# Implement new landing page fourth section according to new ui design

## Why do we need this?

We want to transition to a more innovative and user-friendly design compared to the old one, aiming to increase user attention.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

- Only the fourth section of the landing page should implemented including footer.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=28-1238&mode=design&t=UteNBAQVWXCmz81r-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by mertcanaltin** [comment]
of course you can improve

**Comment by mertcanaltin** [comment]
congrats 🎉 @hsglc
