### ISSUE TITLE
Leave room feature

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#7]
### Tasks

# Implement leave room feature

## Why do we need this?

Users may accidentally enter rooms so they might want to change room.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

Develop leave room feature according to Figma design for ongoing grooming sessions.
There are todos for both server and client side:

For client-side:

You should implement new menu opened when user click to his/her profile name.
After that when user click leave room you should implement new popup.
If user clicks close, close the popup and the menu.
If user clicks leave, you should send event to server and listen it, after that redirect user to home.

For server-side:
You should implement an event handler and clear user from the current grooming session.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=534-5988&mode=design&t=pp8q4x5dfE2RCdAI-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by hsglc** [comment]
Hey @armagandalkiran, Is this task being done? If this is not done, I can do it

**Comment by armagandalkiran** [comment]
Hi @hsglc , @aahmetcakir  is working on the ui part of this task so development task is not ready yet 🤘

**Comment by armagandalkiran** [comment]
hi @hsglc , if you still want to implement this issue it is now ready! I can assign it to you please let me now.

Warning: This is going to be a full-stack development

**Comment by hsglc** [comment]
> hi @hsglc , if you still want to implement this issue it is now ready! I can assign it to you please let me now.
> 
> Warning: This is going to be a full-stack development

hi @armagandalkiran, yeap you can assign it to me.

**Comment by armagandalkiran** [comment]
I assigned it thank you 🚀
