### ISSUE TITLE
Participants enter nickname page

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#70]
### Tasks

# Participants enter nickname page

## Why do we need this?

We want to transition to a more innovative and user-friendly design compared to the old one, aiming to increase user attention.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

- Current design should be replaced by the new one.
- You can land this page by creating a room from an admin side after that copy grooming link and open it in new browser.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=71-5184&mode=design&t=ZA9MrkJBhz7y2M3b-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by emrerenJs** [comment]
Hey everyone!

I think this issue was handled in https://github.com/Trendyol/gurubu/pull/79 pull request. So there is only Join Room text to Enter Room text change required.

If you guys agree, I will wait for the merge before continue to issue.

cc: @armagandalkiran

**Comment by armagandalkiran** [comment]
It can be wait, great idea!  @aahmetcakir @mertcanaltin

**Comment by armagandalkiran** [comment]
@ethsmaa closed this issue in another task :fyi:
