### ISSUE TITLE
Admin create room page

### ISSUE THREAD

**Issue by armagandalkiran** [Trendyol/gurubu#71]
### Tasks

# Admin create room page

## Why do we need this?

We want to transition to a more innovative and user-friendly design compared to the old one, aiming to increase user attention.

## Implementation Considerations

- Pay attention to the use of CSS variables in the codebase.
- Ensure proper naming conventions for properties such as color, font-size, or font-weight when adding them to the variable.scss file.

## Scope

- Current design should be replaced by the new one.

## Design Link

[View Design](https://www.figma.com/file/3Rvo2R5AWAse3O09KtuhZT/GurubuV2?type=design&node-id=71-4667&mode=design&t=ZA9MrkJBhz7y2M3b-0)

## Questions or Issues

If you still have questions, feel free to comment within the relevant issue. You can tag @armagandalkiran and @aahmetcakir for assistance.

**Comment by ethsmaa** [comment]
I can work with this issue

**Comment by armagandalkiran** [comment]
Hi! I assigned it to you 🚀
